version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: starpiscinas-app
    container_name: starpiscinas-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - starpiscinas-network

  web:
    image: nginx:alpine
    container_name: starpiscinas-web
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - starpiscinas-network

networks:
  starpiscinas-network:
    driver: bridge
